ChaChat/config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'
  resources :rooms, only: %i[show new destroy]
  devise_for :users
end

ChaChat/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ChaChat/app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true
  after_create_commit { MessageBroadcastJob.perform_later self }

  belongs_to :user
  belongs_to :room
end

ChaChat/app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
end

ChaChat/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
end

ChaChat/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

ChaChat/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_target_room, only: %i[show destroy]
  def index
    @rooms = Room.all.order(:id)
  end

  def new
    @newroom = Room.create!
    redirect_to root_path, flash: { notice: "「ルーム#{@newroom.id}を作成しました」"}
  end

  def show
    @messages = @room.messages.order(:created_at)
  end

  def destroy
    @room.destroy
    redirect_to root_path, flash: { alert: "「ルーム#{@room.id}」が削除されました" } 
  end

  private

  def set_target_room
    @room = Room.find(params[:id])
  end 
end

ChaChat/app/helpers/application_helper.rb
module ApplicationHelper
  def header_link_item(name, path)
    class_name = 'nav-item'
    class_name << ' active' if current_page?(path)

    content_tag :li, class: class_name do
        link_to name, path, class: 'nav-link'
    end
  end
end

ChaChat/app/helpers/rooms_helper.rb
module RoomsHelper
end

ChaChat/app/views/application/_aside.html.erb
<aside>
  <label for="menu" class="close">X</label>
  <div class="nav-title">
    <%= render 'nav-draw' %>
  </div>
  <nav class="nav-aside">
    <ul class="side-list">
      <li><a>list1</a></li>
      <li><a>list2</a></li>
      <li><a>list3</a></li>
      <li><a>list4</a></li>
      <li><a>list5</a></li>
    </ul>
  </nav>
  <div class="side-footer">
    <a>side footer</a>
  </div>
</aside>

ChaChat/app/views/application/_header.html.erb
<header>
  <%= render 'nav-draw' %>
</header>
<ul class="g-list">
  <% if user_signed_in? %>
    <li><%= link_to  current_user.email, destroy_user_session_path, method: :delete %></li>
    <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
  <% end %>
</ul>

ChaChat/app/views/application/_nav-draw.html.erb
<label for="menu" class="open">🍔</label>
<a class="f-box" href="https://sajiblog.com/" target="_blank" >
  <img class="header-img" src="/assets/saji.png" width="30" height="30" alt="">
  <div class="title">ChaChat</div>
</a>

ChaChat/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChaChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/png" href="/assets/saji.png">
  </head>

  <body>
    <input id="menu" type="checkbox">
    <label for="menu" class="back"></label>
    <%= render 'header' %>
    <%= render 'aside' %>
      <main>
        <%= yield %>
      </main>
  </body>
</html>

ChaChat/app/views/messages/_message.html.erb
<div class='message'>
  <p><%= "#{message.user.email}: #{message.content}" %></p>
</div>

ChaChat/app/views/rooms/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>
<div class="d-flex align-items-center">
  <h1>部屋一覧</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '新規ルーム作成', new_room_path, class: 'btn btn-outline-dark' %>
  </div>
</div>
<hr>
<div class="index-menu">
  <ul>
    <% @rooms.each do |room| %>
      <li class="room-id"><%= link_to "ROOM#{room.id}", room_path(room) %></li>
    <% end %>
  </ul>
</div>

ChaChat/app/views/rooms/show.html.erb
<h1>Chat Room<%= @room.id %></h1>
<div id='messages' data-room_id="<%= @room.id %>">
  <%= render @messages %>
</div>

<hr>
<%= label_tag :content, 'Say something' %><br>
<%= text_field_tag :content, nil, data: { behavior: 'room_speaker' } %>

<div class="f-container">
  <div class="flex-primary"><%= link_to "戻る", root_path, class: 'btn btn-primary' %></div>
  <div class="flex-danger"><%= link_to "削除", room_path, class: 'btn btn-danger', method: :delete %></div>
</div>

ChaChat/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

ChaChat/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>